[paths]
data_path = "data/physics_data.csv"
model_save_path = "models/dynamics_model.pth"
log_dir = "runs"

[data]
test_size = 0.15
val_size = 0.15
batch_size = 64
random_state = 1
normalize = true

[hyperparameters]
num_epochs = 100
learning_rate = 0.001
patience = 15
hidden_dims = [128, 128, 128]
dropout_rate = 0.02